### ISSUE TITLE
JTuple

### ISSUE THREAD

**Issue by Gawdl3y** [SilverIce/JContainers#31]
It would be fantastic if JContainers had a tuple container that could be used for map keys and such. My specific use for this would be to associate Race and Armor objects together.

**Comment by SilverIce** [comment]
My point was to create a function which generates keys from two forms, like "pluginA-formid-pluginB-formid" and use JMap, like `{"hash-or-SHA": value}` or `{"hash-or-SHA": [[two forms], value]}` 
Otherwise (since JC is generic) it's unclear how to compare such complex JTuple keys in case keys contains an objects, whether key should retain an object or contain deep copy of the object, element order should matter (or not?)..

will close for now
