### ISSUE TITLE
Skyrim Special Edition 64bit version

### ISSUE THREAD

**Issue by RealAntithesis** [SilverIce/JContainers#4]
Hi, now that SKSE 64bit for Skyrim Special Edition is well and truly on its way to being finished, are you considering recompiling JContainers for Special Edition?

**Comment by watsonlu** [comment]
I tried it out in SSE, you can compile against it once you copy the scripts to the right location, but it throws errors like this whenever you try to use a function:

    [12/30/2017 - 10:54:22PM] error: Unbound native function "setFlt" called
    [12/30/2017 - 10:54:22PM] error: Unbound native function "getFlt" called

@SilverIce any chance we could get a Skyrim SE version? This plugin saves a tonne of time

**Comment by SilverIce** [comment]
@RealAntithesis 
@watsonlu 

Hi guys. I can help/consult the ones willing to port JContainers onto SSE. It shouldn't be that hard, but I do not play SSE to be able to test it

**Comment by pugwash99** [comment]
I've been looking into to it for a couple of weeks. Got my vs2013 build environment working and have it building (not tested though).

As a complete novice in C++ the biggest issue appears to be the update of the code to be compatible with vs2015 vc140 over vs2013 vc120. There are a few breaking changes between vc120 and vc140 causing the build to fail. 

Then we have the new skse64 which is written in vs2015 vc140 - downgrading it to vc120 results in lots of errors in the main code and upgrading jcontainers to vs140 results in errors due to the breaking changes.

tbh at this point I think the conversion is beyond my talent until I can get my head around C++

**Comment by Neondaze** [comment]
@SilverIce. I would be happy to test your dll in SSE.

On a side note,  a rewrite not be possible what about a 64 bit wrapper? There is a lot of code on this site, but unfortunately my experience using C/C++ is non-existent.

**Comment by ryobg** [comment]
Hello, yet another wannabee here :)

I did some things which made sense for me, but your opinion may vary of course:
- Migrated to MSVC2017 Community.
- Migrated to Boost 1.66 and popped it out of the repo. Old version had troubles to build for MSVC2017.
- Built SKSE64 2.0.6
- Fixed many warnings and build errors. 

BUT!

I see blocking issue with SKSE. This project relies on state callbacks, which SKSE does not implement. I'm not familiar with the functional design of the project, so I cannot deliberately or easily fix this. As consequence the 64-bit DLL cannot be build, hence the API example and Post-build projects.

I forked and made new branch here https://github.com/ryobg/JContainers/tree/port64

Please supervise.

**Comment by ryobg** [comment]
At this time the project seems correctly build for x64.

I have tried to make my changes to minimum, just to be able to compile and fit into the new SKSE 2.0.6. 

Maybe the temporary project paths and configuration are not very well set up, but they looks working and with small tuning they can be tested on a local machine. Anyway, it is not mandatory to do so, as the distribution archive can be used instead.

I do realize that I didn't took the best approach and basically replaced the old SKSE with the new one, thus disallowing the same project to build for the old version of Skyrim and for the new one at the same time. This can be fixed by playing with the project configuration settings (paths mostly). So it is not some major obstacle.

Now, everybody who is willing to have the x64 build of JContainer can either build it himself by going to linked up fork&branch, using MSVC2017 and say Boost 1.66 distro, or I can upload somewhere the distro archive. 

On this stage, only testing and eventually - fixes are needed. I myself, cannot do that as I'm not at all familiar with how this plugin is used in practice. The whole purpose of this migration was for my own amusement. 

I do hope though, that this effort can be of use to somebody. 

Peace and all the best.

**Comment by ryobg** [comment]
FYI:

I, with the help of @pugwash99  and @javierhimura and maybe other unknown users, were able to [alpha release a 64-bit build](https://github.com/ryobg/JContainers/releases/tag/v4.0.0-alpha). There are bunch of, mostly cosmetic, changes which may be not the taste of the original author, but I didn't knew better. 

Currently there is a need for small circle of users willing to trial it out.

**EDIT: Added newer, beta release**
https://github.com/ryobg/JContainers/releases/tag/v4.0.1-beta

Best regards and thank you for the great work.

**Comment by Mikaal69** [comment]
Since Skyrim SE and SKSE64 are updated, the actual Version of jcontainers64 isn't working anymore. Will there be eventually a fix?

**Comment by ryobg** [comment]
@Mikaal69 have you searched for the latest release, in this case 4.1.0? So far, these are on this page: https://github.com/ryobg/JContainers/releases. 

Do read what were the changes between the versions. For example, the latest release, regretfully has no binary compatible co-saves i.e. if you have made a save file with older version (e.g. 4.0.1), it may (but not mandatory) crash/CDT (at worst) your game when loading it with the new version (4.1.0).

Hope this helps.

**Comment by ryobg** [comment]
FYI: https://www.nexusmods.com/skyrimspecialedition/mods/16495
I think issue can be closed now :+1:
